#! /usr/bin/env bash
set -e # exit if something goes wrong

# Install deps
yarn

# Publish a production release
exp publish --release-channel production --non-interactive

# Build Android standalone release
exp build:android --release-channel production --non-interactive --no-publish

# Download the apk
curl -o app.apk "$(exp url:apk --non-interactive)"

fastlane supply --track 'production' --json_key '~/.api-7738836530326696066-539250-c6f11c3abb07.json' --package_name "tech.econn.quirk" --apk "app.apk" --skip_upload_metadata --skip_upload_images --skip_upload_screenshots

# Build a ios standalone release 
exp build:ios --release-channel production --non-interactive --no-publish

# Download the artifact
curl -o app.ipa "$(exp url:ipa --non-interactive)"

# This step assumes you have the following environment variables set
fastlane deliver --verbose --ipa "app.ipa" --skip_screenshots --skip_metadata --user "flaqueeau@gmail.com" --team_name "Evan Conrad"

