export const THOUGHT_SCREEN = "THOUGHT_SCREEN";
export const DISTORTION_SCREEN = "DISTORTION_SCREEN";
export const CHALLENGE_SCREEN = "CHALLENGE_SCREEN";
export const ALTERNATIVE_SCREEN = "ALTERNATIVE_SCREEN";
export const FINISHED_SCREEN = "FINISHED_SCREEN";
export const FEELING_SCREEN = "FEELING_SCREEN";

// Follow-up screens
export const FOLLOW_UP_REQUEST_SCREEN = "FOLLOW_UP_REQUEST_SCREEN";
export const FOLLOW_UP_FEELING_SCREEN = "FOLLOW_UP_FEELING_SCREEN";
export const FOLLOW_UP_FEELING_REVIEW_SCREEN =
  "FOLLOW_UP_FEELING_REVIEW_SCREEN";
export const FOLLOW_UP_NOTE_SCREEN = "FOLLOW_UP_NOTE_SCREEN";

// Feedback
export const FEEDBACK_SCREEN = "FEEDBACK_SCREEN";
export const FEEDBACK_LEAVE_REVIEW = "FEEDBACK_LEAVE_REVIEW";

// Checkup
export const CHECKUP_SUMMARY_SCREEN = "CHECKUP_SUMMARY_SCREEN";
