export const THOUGHT_SCREEN = "THOUGHT_SCREEN";
export const DISTORTION_SCREEN = "DISTORTION_SCREEN";
export const CHALLENGE_SCREEN = "CHALLENGE_SCREEN";
export const ALTERNATIVE_SCREEN = "ALTERNATIVE_SCREEN";
export const FINISHED_SCREEN = "FINISHED_SCREEN";
export const RESULT_SCREEN = "RESULT_SCREEN";
export const PAYMENT_PROTECTED_SCREEN = "PAYMENT_PROTECTED_SCREEN";
