export const GOAL_SCREEN = "GOAL_SCREEN";
export const CONDITION_SCREEN = "CONDITION_SCREEN";
export const FAMILIARITY_SCREEN = "FAMILIARITY_SCREEN";
export const NOTIFICATION_SCREEN = "NOTIFICATION_SCREEN";
export const CHECKUP_PROMPT_SCREEN = "CHECKUP_PROMPT_SCREEN";
export const WELCOME_SCREEN = "WELCOME_SCREEN";
export const ANXIETY_CHECK_SCREEN = "ANXIETY_CHECK_SCREEN";
export const PREDICTION_PROMPT_SCREEN = "PREDICTION_PROMPT_SCREEN";
