export const GOAL_SCREEN = "GOAL_SCREEN";
export const CONDITION_SCREEN = "CONDITION_SCREEN";
export const FAMILIARITY_SCREEN = "FAMILIARITY_SCREEN";
export const NOTIFICATION_SCREEN = "NOTIFICATION_SCREEN";
