# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(
      build_number: app_store_build_number + 1,
      xcodeproj: "quirk.xcodeproj"
    )

    get_certificates           # invokes cert
    get_provisioning_profile   # invokes sigh
    build_app(workspace: "quirk.xcworkspace", scheme: "quirk")
    upload_to_testflight
  end

  lane :release do 
    increment_build_number(
      build_number: app_store_build_number + 1,
      xcodeproj: "quirk.xcodeproj"
    )

    get_certificates           # invokes cert
    get_provisioning_profile   # invokes sigh
    build_app(workspace: "quirk.xcworkspace", scheme: "quirk")
    upload_to_app_store
  end

end
