export const CBT_FORM_SCREEN = "CBTFormScreen";
export const CBT_LIST_SCREEN = "CBTListScreen";
export const CBT_ON_BOARDING_SCREEN = "CBT_ON_BOARDING_SCREEN";
export const EXPLANATION_SCREEN = "EXPLANATION_SCREEN";
export const SETTING_SCREEN = "SETTING_SCREEN";
export const PAYMENT_SCREEN = "PAYMENT_SCREEN";
export const CBT_VIEW_SCREEN = "CBT_VIEW_SCREEN";
export const LOCK_SCREEN = "LOCK_SCREEN";
